endpoints:
  - name: ggrmotor website
    group: website availability
    url: "https://ggrmotor.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"

  - name: ggrmotor www website
    group: website availability
    url: "https://www.ggrmotor.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"

  - name: navbright website
    group: website availability
    url: "https://navbright.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"

  - name: navbright www website
    group: website availability
    url: "https://www.navbright.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"

  - name: ggrmotor SSL certificate
    group: SSL certificates
    url: "https://ggrmotor.com"
    interval: 1h
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 720h"

  - name: ggrmotor www SSL certificate
    group: SSL certificates
    url: "https://www.ggrmotor.com"
    interval: 1h
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 720h"

  - name: navbright SSL certificate
    group: SSL certificates
    url: "https://navbright.com"
    interval: 1h
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 720h"

  - name: navbright www SSL certificate
    group: SSL certificates
    url: "https://www.navbright.com"
    interval: 1h
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 720h"

  - name: ggrmotor domain expiry
    group: domain expiry
    url: "https://ggrmotor.com"
    interval: 12h
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"

  - name: navbright domain expiry
    group: domain expiry
    url: "https://navbright.com"
    interval: 12h
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"

  - name: ggrmotor DNS
    group: DNS resolution
    url: "1.1.1.1"
    interval: 5m
    dns:
      query-name: "ggrmotor.com"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"

  - name: navbright DNS
    group: DNS resolution
    url: "1.1.1.1"
    interval: 5m
    dns:
      query-name: "navbright.com"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
