endpoints:
  - name: ggrmotor
    group: websites
    url: "https://ggrmotor.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 168h"
      - "[DOMAIN_EXPIRATION] > 720h"

  - name: ggrmotor-www
    group: websites
    url: "https://www.ggrmotor.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 168h"

  - name: ggrmotor-dns
    group: websites
    url: "1.1.1.1"
    interval: 5m
    dns:
      query-name: "ggrmotor.com"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"

  - name: navbright
    group: websites
    url: "https://navbright.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 168h"
      - "[DOMAIN_EXPIRATION] > 720h"

  - name: navbright-www
    group: websites
    url: "https://www.navbright.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 168h"

  - name: navbright-dns
    group: websites
    url: "1.1.1.1"
    interval: 5m
    dns:
      query-name: "navbright.com"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
